"""Adds fields to support conversation threads.

Revision ID: 0b523354f8b0
Revises: 521e3a6b77d0
Create Date: 2022-11-22 12:26:01.313896

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0b523354f8b0"
down_revision = "521e3a6b77d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation", sa.Column("thread_id", sa.String(), nullable=True))
    op.add_column("conversation", sa.Column("case_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "conversation", "case", ["case_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "conversation", type_="foreignkey")
    op.drop_column("conversation", "case_id")
    op.drop_column("conversation", "thread_id")
    # ### end Alembic commands ###
