"""Adds fields to support conversation threads.

Revision ID: 0b523354f8b0
Revises: bd61c1e1e7cd
Create Date: 2022-11-22 12:26:01.313896

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0b523354f8b0"
down_revision = "bd61c1e1e7cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "search_filter",
        "type",
        nullable=True,
        new_column_name="subject",
    )
    op.execute("update search_filter set subject = 'Incident'")
    op.add_column("notification", sa.Column("subject", sa.String(), nullable=True))
    op.execute("update notification set subject = 'Incident'")
    op.alter_column("notification", "subject", nullable=False)
    op.execute("update search_filter set creator_id = 1")

    op.add_column("conversation", sa.Column("thread_id", sa.String(), nullable=True))
    op.add_column("conversation", sa.Column("case_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "conversation", "case", ["case_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "search_filter",
        "subject",
        nullable=True,
        new_column_name="type",
    )
    op.drop_column("notification", "subject")
    op.drop_constraint(None, "conversation", type_="foreignkey")
    op.drop_column("conversation", "case_id")
    op.drop_column("conversation", "thread_id")
    # ### end Alembic commands ###
